### ISSUE TITLE
Provide clear instructions to install NVIDIA Nsight Systems

### ISSUE THREAD

**Issue by abhijeetdhakane** [NERSC/sc22-dl-tutorial#5]
Nvidia Official site restricting to download NVIDIA Nsight Systems tool. Can you please provide more instructions to DOWNLOAD and INSTALL NVIDIA Nsight Systems on Mac OS.

**Comment by sparticlesteve** [comment]
The instructions do mention the account requirement:

> You may need to sign up and create a login to NVIDIA's developer program if you do not already have an account to access the download.

Is that what you're referring to, or is something else not clear?

Note this repo is still under development for the upcoming tutorial at SC on Sunday.

**Comment by romerojosh** [comment]
On the page linked in the `README.md` section [here](https://github.com/NERSC/sc22-dl-tutorial#installing-nsight-systems), expand the first row labelled `Nsight Systems` (corresponding to version 2022.4). On the right side of the expanded row, you will see various download options. Select the one labelled ` Nsight Systems 2022.4.1 (macOS Host)`. Hope that clears things up!

**Comment by abhijeetdhakane** [comment]
After login into my account, I could not download the NVIDIA Insight system software, says "Access Denied."

**Comment by sparticlesteve** [comment]
sorry, not sure why that would happen. This is the official way to download nsys. Maybe there's an issue with your developer account, or maybe it wasn't fully activated...?
